=== Pabet/Modeling_Simulation/shapes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="shapes" type="shapesType"/>
  <xs:complexType name="delta-tType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="t"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="end-timeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="t"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="factorType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="domain-sizeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="x"/>
        <xs:attribute type="xs:string" name="y"/>
        <xs:attribute type="xs:string" name="z"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="rcutoffType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="x1-boundary-conditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="x2-boundary-conditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="y1-boundary-conditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="y2-boundary-conditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="z1-boundary-conditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="z2-boundary-conditionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="brownian-motionType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bol"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="initial-temperatureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="n-thermostatType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="t"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="target-temperatureType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="temperature-differenceType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="gravitationType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="r0Type">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="kType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="fz-upType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="parallelisation-methodType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="force-calculation-methodType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="rlType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="settingsType">
    <xs:sequence>
      <xs:element type="delta-tType" name="delta-t"/>
      <xs:element type="end-timeType" name="end-time"/>
      <xs:element type="factorType" name="factor"/>
      <xs:element type="domain-sizeType" name="domain-size"/>
      <xs:element type="rcutoffType" name="rcutoff"/>
      <xs:element type="x1-boundary-conditionType" name="x1-boundary-condition"/>
      <xs:element type="x2-boundary-conditionType" name="x2-boundary-condition"/>
      <xs:element type="y1-boundary-conditionType" name="y1-boundary-condition"/>
      <xs:element type="y2-boundary-conditionType" name="y2-boundary-condition"/>
      <xs:element type="z1-boundary-conditionType" name="z1-boundary-condition"/>
      <xs:element type="z2-boundary-conditionType" name="z2-boundary-condition"/>
      <xs:element type="brownian-motionType" name="brownian-motion"/>
      <xs:element type="initial-temperatureType" name="initial-temperature"/>
      <xs:element type="n-thermostatType" name="n-thermostat"/>
      <xs:element type="target-temperatureType" name="target-temperature"/>
      <xs:element type="temperature-differenceType" name="temperature-difference"/>
      <xs:element type="gravitationType" name="gravitation"/>
      <xs:element type="r0Type" name="r0"/>
      <xs:element type="kType" name="k"/>
      <xs:element type="fz-upType" name="fz-up"/>
      <xs:element type="parallelisation-methodType" name="parallelisation-method"/>
      <xs:element type="force-calculation-methodType" name="force-calculation-method"/>
      <xs:element type="rlType" name="rl"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
  </xs:complexType>
  <xs:complexType name="write-checkpointType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bol"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="read-checkpointType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bol"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="write-checkpoint-timeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="t"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="checkpointType">
    <xs:sequence>
      <xs:element type="write-checkpointType" name="write-checkpoint"/>
      <xs:element type="read-checkpointType" name="read-checkpoint"/>
      <xs:element type="write-checkpoint-timeType" name="write-checkpoint-time"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
  </xs:complexType>
  <xs:complexType name="typeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="epsilonType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="sigmaType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="centreType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="x"/>
        <xs:attribute type="xs:string" name="y"/>
        <xs:attribute type="xs:string" name="z"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="radiusType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="velocityType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="x" use="optional"/>
        <xs:attribute type="xs:string" name="y" use="optional"/>
        <xs:attribute type="xs:string" name="z" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="massType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="hType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="val" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="sphereType">
    <xs:sequence>
      <xs:element type="typeType" name="type"/>
      <xs:element type="epsilonType" name="epsilon"/>
      <xs:element type="sigmaType" name="sigma"/>
      <xs:element type="centreType" name="centre"/>
      <xs:element type="radiusType" name="radius"/>
      <xs:element type="velocityType" name="velocity"/>
      <xs:element type="massType" name="mass"/>
      <xs:element type="hType" name="h"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id"/>
  </xs:complexType>
  <xs:complexType name="right-top-pointType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="x" use="optional"/>
        <xs:attribute type="xs:string" name="y" use="optional"/>
        <xs:attribute type="xs:string" name="z" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="side-lengthsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="x" use="optional"/>
        <xs:attribute type="xs:string" name="y" use="optional"/>
        <xs:attribute type="xs:string" name="z" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="membraneType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="bol" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="cuboidType">
    <xs:sequence>
      <xs:element type="typeType" name="type"/>
      <xs:element type="epsilonType" name="epsilon"/>
      <xs:element type="sigmaType" name="sigma"/>
      <xs:element type="right-top-pointType" name="right-top-point"/>
      <xs:element type="side-lengthsType" name="side-lengths"/>
      <xs:element type="velocityType" name="velocity"/>
      <xs:element type="massType" name="mass"/>
      <xs:element type="hType" name="h"/>
      <xs:element type="membraneType" name="membrane"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>
  <xs:complexType name="shapesType">
    <xs:sequence>
      <xs:element type="settingsType" name="settings" minOccurs="1" maxOccurs="1"/>
      <xs:element type="checkpointType" name="checkpoint" minOccurs="0" maxOccurs="1"/>
      <xs:element type="sphereType" name="sphere" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element type="cuboidType" name="cuboid" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Pabet/Modeling_Simulation/supercoolingArgon.xml
<?xml version="1.0"?>

<shapes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="shapes.xsd">
	<settings id="simulationSettings">
		<delta-t  t="0.001"  />
		<end-time t="100.0"   />
		<factor val="0.0"/>
	        <domain-size x="9.2" y="9.2" z="9.2" />
        	<rcutoff  val="2.3"            />
		<x1-boundary-condition val="periodic"/>
		<x2-boundary-condition val="periodic"   />
		<y1-boundary-condition val="periodic"  />
		<y2-boundary-condition val="periodic"  />
		<z1-boundary-condition val="periodic"  />
		<z2-boundary-condition val="periodic"  />
		<brownian-motion bol="true" />
		<initial-temperature val="3.0" />
		<n-thermostat t="25.0" />
		<target-temperature val="0.02" />
		<temperature-difference val="2.5e-3" />
		<gravitation val="0.0" />
		<r0 val="0.0"/>
		<k val="0.0"/>
		<fz-up val="0.0" />
		<parallelisation-method val = "sparse" />
		<force-calculation-method  val = "Smoothed LJ"  />
		<rl val="1.9"/>
	</settings>

	<checkpoint id="checkpointSettings">
		<write-checkpoint bol="false" />
		<read-checkpoint  bol="true" />
		<write-checkpoint-time t="0.0" />
	</checkpoint>
</shapes>

=== Pabet/Modeling_Simulation/input2.xml
<?xml version="1.0"?>

<shapes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xsi:noNamespaceSchemaLocation="shapes.xsd">

<settings id="simulationSettings">
<delta-t  t="0.0005"  />

<end-time t="20.0"   />

<factor val="0.1"/>
  
<domain-size x="180.0" y="90.0" z="0.0" />

<rcutoff  val="3.0"            />

<x1-boundary-condition val="outflow" />

<x2-boundary-condition val="outflow" />

<y1-boundary-condition val="outflow" />

<y2-boundary-condition val="outflow" />

<z1-boundary-condition val="outflow"/>

<z2-boundary-condition val="outflow"/>
	
<brownian-motion bol="true" />

<initial-temperature val="0.5" />

<n-thermostat t="1000.0" />

<target-temperature val="0.5" />

		<temperature-difference val="0.0" />

		<gravitation val="0" />
	
</settings>
<checkpoint id="checkpointSettings">
	
<write-checkpoint bol="true" />

		<read-checkpoint  bol="false" />

		<write-checkpoint-time t="15.0" />

	</checkpoint>
<cuboid id="object1">
	<type val="1"/>
	<c-epsilon val="5.0"/>
	<c-sigma val="1.0"/>
	<right-top-point x="20" y="20" z="0"/>
	<side-lengths x="100" y="20" z="1"/>
	<velocity x="0.0" y="0.0" z="0.0"/>
	<mass val="1.0"/>
	<h val="1.1225"/>
</cuboid>
	<cuboid id="object2">
		<type val="2"/>
		<c-epsilon val="5.0"/>
		<c-sigma val="1.0"/>
		<right-top-point x="70" y="60" z="0"/>
		<side-lengths x="20" y="20" z="1"/>
		<velocity x="0.0" y="-10.0" z="0.0"/>
		<mass val="1.0"/>
		<h val="1.1225"/>
	</cuboid>



</shapes>

=== Pabet/Modeling_Simulation/shapes.xml
<?xml version="1.0"?>
<shapes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="shapes.xsd">
	<settings id="simulationSettings">
		<delta-t  t="0.0005"  />
		<end-time t="25.0"   />
		<factor val="0.0"/>
        <domain-size x="63.0" y="36.0" z="0.0" />
        <rcutoff  val="3.0"            />
		<x1-boundary-condition val="reflecting"/>
		<x2-boundary-condition val="outflow"   />
		<y1-boundary-condition val="periodic"  />
		<y2-boundary-condition val="periodic"  />
		<z1-boundary-condition val="periodic"  />
		<z2-boundary-condition val="periodic"  />
		<brownian-motion bol="true" />
		<initial-temperature val="40.0" />
		<n-thermostat t="1000.0" />
		<target-temperature val="40.0" />
		<temperature-difference val="0.0" />
		<gravitation val="-12.44" />
		<r0 val="2.2"/>
		<k val="300.0"/>
		<fz-up val="0.8" />
		<parallelisation-method val = "sparse" />
		<force-calculation-method  val = "LJ"  />
	</settings>

	<checkpoint id="checkpointSettings">
		<write-checkpoint bol="true" />
		<read-checkpoint  bol="false" />
		<write-checkpoint-time t="5.0" />
	</checkpoint>

	<sphere id="sphere1">
		<type val="1.0" 						  />
		<epsilon val="5.0"                      />
		<sigma val="1.0"                        />
		<centre   x="10.0" y="0.0" z="0.0"        />
		<radius   val="5.0"                       />
		<velocity x="0.0" y="0.0" z="0.0"         />
		<mass 	  val="1.0" 	                  />
		<h		  val="1.025"                     />
	</sphere>

	<cuboid id="liquid1">
		<type val="3.0" />
		<epsilon val="1.0"/>
		<sigma val="1.0"/>
		<right-top-point   x="32.1" y="2.0" z="0.0"        />
		<side-lengths   x="50.0" y="14.0" z="1.0"               />
		<velocity x="0.0" y="0.0" z="0.0"         />
		<mass 	  val="1.0" 	                  />
		<h		  val="1.2"                     />
		<membrane bol="false" />
	</cuboid>

	<cuboid id="liquid2">
		<type val="2.0"/>
		<epsilon val="1.0"/>
		<sigma val="0.9412"/>
		<right-top-point   x="32.1" y="19.0" z="0.0"        />
		<side-lengths   x="50.0" y="14.0" z="1.0"               />
		<velocity x="0.0" y="0.0" z="0.0"         />
		<mass 	  val="2.0" 	                  />
		<h		  val="1.2"                     />
		<membrane bol="false" />
	</cuboid>

</shapes>

=== Pabet/Modeling_Simulation/5-2-input.xml
<?xml version="1.0"?>
<shapes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="shapes.xsd">
	<settings id="simulationSettings">
		<delta-t  t="0.0005"  />
		<end-time t="100.0"   />
		<factor val="0.0"/>
		<domain-size x="60.0" y="24.0" z="51.0" />
        <rcutoff  val="3.0"            />
		<x1-boundary-condition val="periodic"/>
		<x2-boundary-condition val="periodic"   />
		<y1-boundary-condition val="reflecting"  />
		<y2-boundary-condition val="reflecting"  />
		<z1-boundary-condition val="none"  />
		<z2-boundary-condition val="none"  />
		<brownian-motion bol="true" />
		<initial-temperature val="40.0" />
		<n-thermostat t="1000.0" />
		<target-temperature val="0.0" />
		<temperature-difference val="0.0" />
		<gravitation val="-12.44" />
		<r0 val="0.0"/>
		<k val="0.0"/>
		<fz-up val="0.0" />
		<parallelisation-method val = "sparse" />
		<force-calculation-method  val = "LJ"  />
		<rl val="0.0" />
	</settings>

	<checkpoint id="checkpointSettings">
		<write-checkpoint bol="false" 		     />
		<read-checkpoint  bol="false" 		     />
		<write-checkpoint-time t="0.0" 		     />
	</checkpoint>

	<cuboid id="liquid1">
		<type 	  	  val="1.0" 		     />
		<epsilon 	  val="2.0"		     />
		<sigma 		  val="1.15"		     />
		<right-top-point  x="0.6" y="0.6" z="0.6"    />
		<side-lengths     x="48.0" y="9.0" z="42.0"  />
		<velocity 	  x="0.0" y="0.0" z="0.0"    />
		<mass 	  	  val="14.0" 	             />
		<h		  	  val="1.2"                  />
		<membrane 	  bol="true" 		     />
	</cuboid>

	<cuboid id="liquid2">
		<type 	  	  val="2.0" 		     />
		<epsilon 	  val="2.0"		     />
		<sigma 		  val="1.15"		     />
		<right-top-point  x="0.6" y="11.4" z="0.6"    />
		<side-lengths     x="48.0" y="9.0" z="42.0"  />
		<velocity 	  x="0.0" y="0.0" z="0.0"    />
		<mass 	  	  val="30.0" 	             />
		<h		  	  val="1.2"                  />
		<membrane 	  bol="true" 		     />
	</cuboid>

</shapes>

=== Pabet/Modeling_Simulation/input3.xml
<?xml version="1.0"?>

<shapes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"

xsi:noNamespaceSchemaLocation="shapes.xsd">

<settings id="simulationSettings">
<delta-t  t="0.0005"  />

<end-time t="40.0"   />

<factor val="0.1"/>
  
<domain-size x="303.0" y="180.0" z="0.0" />

<rcutoff  val="3.0"            />
   
<horizontal-boundary-condition val="reflecting" />

<vertical-boundary-condition val="reflecting" />
	
<brownian-motion bol="true" />

<initial-temperature val="0.5" />

<n-thermostat t="0.0" />

<target-temperature val="0.5" />

		<temperature-difference val="0.0" />

		<gravitation val="-12.44" />
	
</settings>
<checkpoint id="checkpointSettings">
	
<write-checkpoint bol="false" />

		<read-checkpoint  bol="true" />

		<write-checkpoint-time t="0.0" />

	</checkpoint>

<sphere id="sphere1">
	
	<s-epsilon val="1.0"                      />

		<s-sigma val="1.2"                        />

		<centre   x="150.0" y="150.0" z="0.0"        />

		<radius   val="20.0"                       />

		<velocity x="0.0" y="0.0" z="0.0"         />

		<mass 	  val="1.0" 	                  />
		
<h		  val="1.2"                     />

	</sphere>

</shapes>
